config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  get 'about', to: 'pages#about'

  resources :articles do
    member do
      put "like", to: "articles#upvote"
      put "dislike", to: "articles#downvote"
    end
    resources :comments, only: [:create, :destroy]
  end

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]

  mount ActionCable.server => '/cable'

  get '/chat', to: 'chatrooms#show'
  resources :messages, only: [:create]
end

app/models/article.rb
class Article <ActiveRecord::Base
  belongs_to :user, optional: true
  has_many :article_categories
  has_many :comments, dependent: :destroy
  has_many :categories, through: :article_categories
  mount_uploader :picture, PictureUploader
  mount_uploader :video, VideoUploader
  validates :title, presence: true, length: {minimum: 3, maximum: 5000}
  validates :description, presence: true, length: {minimum: 10, maximum: 100000}
  validates :user_id, presence: true
  default_scope -> { order(updated_at: :desc)}
  acts_as_votable

  #def score
   # self.get_upvotes.size - self.get_downvotes.size
  #end

  def self.search(search)
    where("title LIKE ?", "%#{search}%")
  end
end

app/controllers/articles_controller.rb
class ArticlesController <ApplicationController

  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    #@articles = Article.paginate(page: params[:page], per_page: 20)
    @articles = Article.search(params[:search]).paginate(page: params[:page], per_page: 25).order("created_at DESC")
  end

  def show
    @articles = Article.all
    @comment = Comment.new
    @comments = @article.comments.paginate(page:params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "News was successfully Uploaded"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:success] = "News was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:danger] = "News was successfully deleted"
    redirect_to articles_path
  end

  def upvote
    @article = Article.find(params[:id])
    @article.upvote_by current_user
    redirect_to articles_path
  end

  def downvote
    @article = Article.find(params[:id])
    @article.downvote_by current_user
    redirect_to articles_path
  end

  private
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, :picture, :video, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user and !current_user.admin?
      flash[:danger] = "You can only Edit or Delete your own news"
      redirect_to root_path
    end
  end
end

app/views/articles/_article.html.erb
<section id="sliderSection">
  <div class="row">
    <% obj.in_groups(2,false).each do |group| %>
        <div class="col-lg-4 col-md-4 col-sm-4">

          <% group.each do |article| %>
              <div class="slick_slider">
                <div class="single_iteam">
                  <%= link_to article_path(article) do %>
                      <%= image_tag (article.picture.url) if article.picture? %>
                  <% end %>

                  <div class="slider_article">
                    <h2><%= link_to article.title, article_path(article), class: "slider_tittle" %></h2>
                    <p><%= article.user.username if article.user %>  -
                      <span class="quiet"><small><%= time_ago_in_words(article.created_at) %> ago</small></span>
                    </p><br/>
                    <p><%= truncate article.description, length:75 %></p><br/>

                    <div class="article-body-like">
                      <%= link_to like_article_path(article), method: :put do %>
                          <i class="glyphicon glyphicon-thumbs-up" style="color: white"></i>&nbsp;
                          <b style="color: white"><%= article.get_upvotes.size %></b>
                      <% end %>&nbsp;&nbsp;
                      <%= link_to dislike_article_path(article), method: :put do %>
                          <i class="glyphicon glyphicon-thumbs-down" style="color: white"></i>&nbsp;
                          <b style="color: white "><%= article.get_downvotes.size %></b>
                      <% end %>&nbsp;
                      <b style="color: white">|&nbsp;<%= pluralize(article.comments.count, 'Comment') %></b>
                    </div>
                  </div>
                </div>
              </div>
          <% end %>
        </div>
    <% end %>

    <div class="col-lg-4 col-md-4 col-sm-4">
      <div class="latest_post">
        <h2><span>Latest News</span></h2>
        <div class="latest_post_container">
          <!--<ul>
            <li>
              <#% obj.each do |art| %>
                  <div class="row" style="margin-bottom: 10px">
                    <div class="media col-md-4">
                      <%#= link_to article_path(art) do %>
                          <%#= image_tag(art.picture.url, height: '85', width: '100') if art.picture?%>
                      <#% end %>
                    </div>
                    <div class="col-md-8" style="padding: 0;"><b><i style="font-size: small"><h4><%#= link_to art.title, article_path(art) %></h4></i></b></div>
                  </div>
              <#% end %>
            </li>
          </ul>
          <ul>-->
          <marquee scrolldelay="" scrollamount="4" direction="up" onmouseover="this.setAttribute('scrollamount', 4, 0);" onmouseout="this.setAttribute('scrollamount', 4, 0);" behavior="scroll" height="400">
            <% obj.each do |art| %>
              <div class="row" style="margin-bottom: 10px">
                <div class="media col-md-4">
                  <%= link_to article_path(art) do %>
                    <%= image_tag(art.picture.url, height: '85', width: '100') if art.picture?%>
                  <% end %>
                </div>
                <div class="col-md-8" style="padding: 0;"><b><i style="font-size: small"><h4><%= link_to art.title, article_path(art) %></h4></i></b></div>
              </div>
            <% end %>
          </marquee>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="sliderSection">
  <div class="row">
    <div class="col-lg-8 col-md-8 col-sm-8">
      <div class="latest_post">
        <h2><span>Videos</span></h2>
        <% obj.in_groups_of(1,false).each do |group| %>
            <div class="col-lg-6 col-md-6 col-sm-6">
              <% group.each do |article| %>
                  <% if article.video? %>
                    <div class="slick_slider">
                      <div class="single_iteam" style="height: 200px; width: 250px;">
                        <%= (video_tag article.video.url, controls: true, type: "video/mp4", height: '200', width: '330') if article.video? %>
                      </div>
                    </div>
                  <% end %>
              <% end %>
            </div>
        <% end %>
      </div>
    </div>

    <div class="col-lg-4 col-md-4 col-sm-4">
      <div class="latest_post">
        <h2><span>Latest Videos</span></h2>
        <div class="latest_post_container">
          <marquee scrolldelay="" scrollamount="4" direction="up" onmouseover="this.setAttribute('scrollamount', 4, 0);" onmouseout="this.setAttribute('scrollamount', 4, 0);" behavior="scroll" height="400">
              <% obj.each do |art| %>
                  <% if art.video? %>
                      <div class="row" style="margin-bottom: 10px">
                        <div class="media col-md-4">
                          <%= link_to article_path(art) do %>
                              <%= video_tag(art.video.url, height: '85', width: '100') if art.video?%>
                          <% end %>
                        </div>
                        <div class="col-md-8" style="padding: 0;"><b><i style="font-size: small"><h4><%= link_to art.title, article_path(art) %></h4></i></b></div>
                      </div>
                  <% end %>
              <% end %>
           </marquee>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/articles/_cat.html.erb
<section id="sliderSection">
  <div class="row">
    <% obj.in_groups(2,false).each do |group| %>
        <div class="col-lg-4 col-md-4 col-sm-4">

          <% group.each do |article| %>
              <div class="slick_slider">
                <div class="single_iteam">
                  <%= link_to article_path(article) do %>
                      <%= image_tag (article.picture.url) if article.picture? %>
                  <% end %>

                  <div class="slider_article">
                    <h2><%= link_to article.title, article_path(article), class: "slider_tittle" %></h2>
                    <p><%= article.user.username if article.user %>  -
                      <span class="quiet"><small><%= time_ago_in_words(article.created_at) %> ago</small></span>
                    </p><br/>
                    <p><%= truncate article.description, length:75 %></p><br/>

                    <div class="article-body-like">
                      <%= link_to like_article_path(article), method: :put do %>
                          <i class="glyphicon glyphicon-thumbs-up" style="color: white"></i>&nbsp;
                          <b style="color: white"><%= article.get_upvotes.size %></b>
                      <% end %>&nbsp;&nbsp;
                      <%= link_to dislike_article_path(article), method: :put do %>
                          <i class="glyphicon glyphicon-thumbs-down" style="color: white"></i>&nbsp;
                          <b style="color: white"><%= article.get_downvotes.size %></b>
                      <% end %>&nbsp;
                      <b style="color: white">|&nbsp;<%= pluralize(article.comments.count, 'Comment') %></b>
                    </div>
                  </div>
                </div>
              </div>
          <% end %>
        </div>
    <% end %>

    <div class="col-lg-4 col-md-4 col-sm-4">
      <div class="latest_post">
        <h2><span>Latest News</span></h2>
        <div class="latest_post_container">
          <!--<ul>
            <li>
              <#% obj.each do |art| %>
                  <div class="row" style="margin-bottom: 10px">
                    <div class="media col-md-4">
                      <%#= link_to article_path(art) do %>
                          <%#= image_tag(art.picture.url, height: '85', width: '100') if art.picture?%>
                      <#% end %>
                    </div>
                    <div class="col-md-8" style="padding: 0;"><b><i style="font-size: small"><h4><%#= link_to art.title, article_path(art) %></h4></i></b></div>
                  </div>
              <#% end %>
            </li>
          </ul>
          <ul>-->
          <marquee scrolldelay="" scrollamount="4" direction="up" onmouseover="this.setAttribute('scrollamount', 4, 0);" onmouseout="this.setAttribute('scrollamount', 4, 0);" behavior="scroll" height="400">
            <% obj.each do |art| %>
                <div class="row" style="margin-bottom: 10px">
                  <div class="media col-md-4">
                    <%= link_to article_path(art) do %>
                        <%= image_tag(art.picture.url, height: '85', width: '100') if art.picture?%>
                    <% end %>
                  </div>
                  <div class="col-md-8" style="padding: 0;"><b><i style="font-size: small"><h4><%= link_to art.title, article_path(art) %></h4></i></b></div>
                </div>
            <% end %>
          </marquee>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="sliderSection">
  <div class="row">
    <div class="col-lg-8 col-md-8 col-sm-8">
      <div class="latest_post">
        <h2><span>Videos</span></h2>
        <% obj.in_groups_of(1,false).each do |group| %>
            <div class="col-lg-6 col-md-6 col-sm-6">
              <% group.each do |article| %>
                  <% if article.video? %>
                      <div class="slick_slider">
                        <div class="single_iteam" style="height: 200px; width: 250px;">
                          <%= (video_tag article.video.url, controls: true, type: "video/mp4", height: '200', width: '330') if article.video? %>
                        </div>
                      </div>
                  <% end %>
              <% end %>
            </div>
        <% end %>
      </div>
    </div>

    <div class="col-lg-4 col-md-4 col-sm-4">
      <div class="latest_post">
        <h2><span>Latest Videos</span></h2>
        <div class="latest_post_container">
          <marquee scrolldelay="" scrollamount="4" direction="up" onmouseover="this.setAttribute('scrollamount', 4, 0);" onmouseout="this.setAttribute('scrollamount', 4, 0);" behavior="scroll" height="400">
            <% obj.each do |art| %>
                <% if art.video? %>
                    <div class="row" style="margin-bottom: 10px">
                      <div class="media col-md-4">
                        <%= link_to article_path(art) do %>
                            <%= video_tag(art.video.url, height: '85', width: '100') if art.video?%>
                        <% end %>
                      </div>
                      <div class="col-md-8" style="padding: 0;"><b><i style="font-size: small"><h4><%= link_to art.title, article_path(art) %></h4></i></b></div>
                    </div>
                <% end %>
            <% end %>
          </marquee>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/articles/_f.html.erb
<% obj.each do |article| %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
          <div class="article-title">
            <%= link_to article.title, article_path(article) %>
          </div>

          <div class="article-image-details">
            <%= (image_tag article.picture.url, size: "275x200") if article.picture? %>
          </div>

          <!--<div class="article-meta-details">
            #video_tag article.video_url(:medium), controls: true, type: "video/mp4" if article.video? %>
          </div>-->

          <%#video_tag @post.video.url(:medium), controls: true, type: "video/mp4" %>

          <div class="article-body">
            <%= truncate(article.description, length: 100) %>
            <div class="article-meta-details">
              <small>Created by: <%= article.user.username if article.user %>,
                <%= time_ago_in_words(article.created_at) %> ago,
                last_updated: <%= time_ago_in_words(article.updated_at) %> ago
              </small>
            </div>
          </div>

          <% if article.categories.any? %>
              <p>Categories: <%= render article.categories %></p>
          <% end %>

          <% if logged_in? && (current_user == article.user || current_user.admin?) %>
              <div class="article-actions">
                <%= link_to "Edit this Article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
                <%= link_to "Delete this article", article_path(article), method: :delete,
                            data: {confirm: "Are you sure you want to delete the article?"},
                            class: "btn btn-xs btn-danger" %>
              </div>
          <% end %>

          <div class="article-body">
            <%= link_to like_article_path(article), method: :put do %>
                <i class="glyphicon glyphicon-thumbs-up"></i>&nbsp;
                <%= article.get_upvotes.size %>
            <% end %>&nbsp;&nbsp;
            <%= link_to dislike_article_path(article), method: :put do %>
                <i class="glyphicon glyphicon-thumbs-down"></i>&nbsp;
                <%= article.get_downvotes.size %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
  <div class="col-xs-12">
        <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
          <div class="form-group">
            <div class="control-label col-sm-2">
              <%= f.label :title %>
            </div>

            <div class="col-sm-8">
              <%= f.text_field :title, class: "form-control", placeholder: "Title of News", autofocus: true %>
            </div>
          </div>

        <div class="form-group">
          <div class="control-label col-sm-2">
              <%= f.label :description %><br/>
          </div>

          <div class="col-sm-8">
              <%= f.text_area :description,rows:10, class: "form-control", placeholder: "Description of News" %>
          </div>
        </div>

        <div class="form-group">
          <div class="rows">
          <div class="col-sm-offset-2 col-sm-8">
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
              <%= cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
            <% end %>
          </div>
          </div>
        </div>


        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :Image %>
          </div>

          <div class="col-sm-8">
            <%= f.file_field :picture %>
          </div>
        </div>

        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :Video %>
          </div>

          <div class="col-sm-8">
            <%= f.file_field :video %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
              <%= f.submit  class: "btn btn-primary btn-lg"%>
          </div>
        </div>

    <% end %>

    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to "Cancel request and return to News Listing", articles_path %> ]
    </div>
  </div>
</div>

app/views/articles/_oldart.html.erb
<section id="sliderSection">
  <div class="row">
    <div class="col-lg-8 col-md-8 col-sm-8">
      <% obj.each do |article| %>
          <div class="slick_slider">
            <div class="single_iteam">
              <%= link_to article_path(article) do %>
                  <%= image_tag (article.picture.url) if article.picture? %>
              <% end %>

              <div class="slider_article">
                <h2><%= link_to article.title, article_path(article), class: "slider_tittle" %></h2>
                <p><%= article.user.username if article.user %>  -
                  <span class="quiet"><small><%= time_ago_in_words(article.created_at) %> ago</small></span>
                </p><br/>
                <p><%= truncate article.description, length:100 %></p><br/>

                <div class="article-body-like" style="color: #ffffff">
                  <%= link_to like_article_path(article), method: :put do %>
                      <i class="glyphicon glyphicon-thumbs-up"></i>&nbsp;
                      <%= article.get_upvotes.size %>
                  <% end %>&nbsp;&nbsp;
                  <%= link_to dislike_article_path(article), method: :put do %>
                      <i class="glyphicon glyphicon-thumbs-down"></i>&nbsp;
                      <%= article.get_downvotes.size %>
                  <% end %>
                </div>

              </div>
            </div>
          </div>
      <% end %>
    </div>

    <div class="col-lg-4 col-md-4 col-sm-4">
      <div class="latest_post">
        <h2><span>Latest News</span></h2>
        <div class="latest_post_container">
          <ul class="latest_postnav">
            <li>
              <% obj.each do |art| %>
                  <div class="row" style="margin-bottom: 10px">
                    <div class="media col-md-4">
                      <%= link_to article_path(art) do %>
                          <%= image_tag(art.picture.url, height: '85', width: '100') if art.picture?%>
                      <% end %>
                    </div>
                    <div class="col-md-8" style="padding: 0;"><h4><%= link_to art.title, article_path(art) %></h4></div>
                  </div>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div class="col-lg-4 col-md-4 col-sm-4">
      <div class="latest_post">
        <h2><span>Popular News</span></h2>
        <div class="latest_post_container">
          <ul class="latest_postnav">
            <li>
              <% obj.each do |art| %>
                  <div class="row" style="margin-bottom: 10px">
                    <div class="media col-md-4">
                      <%= link_to article_path(art) do %>
                          <%= image_tag(art.picture.url, height: '85', width: '100') if art.picture?%>
                      <% end %>
                    </div>
                    <div class="col-md-8" style="padding: 0;"><h4><%= link_to art.title, article_path(art) %></h4></div>
                  </div>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/articles/edit.html.erb
<h1 align="center">Edit Existing Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<!--<h1 align="center">Listing all articles</h1>

<div align="center">
  <# will_paginate %>
</div>

<# render 'article', obj: @articles %>

<div align="center">
  <%#= will_paginate %>
</div>-->


<%= render 'article', obj: @articles %>


<% if @articles.blank? %>
    <h4>There are no news containing the term <%= params[:search] %>.</h4>
<% end %>


<div align="center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center">Create a News</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<section id="contentSection">
  <div class="row">
    <div class="col-lg-8 col-md-8 col-sm-8">
      <div class="left_content">
        <div class="single_page">
          <ol class="breadcrumb">
            <li><%= link_to "Home", root_path %></li>
            <li><%= render @article.categories %></li>

            <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
                <%= link_to "", article_path(@article), method: :delete,
                            data: { confirm: "Are you sure you want to delete the article?"},
                            class: "glyphicon glyphicon-trash icon", style: "color" %>
                <%= link_to "", edit_article_path(@article), class: "glyphicon glyphicon-pencil icon" %>
            <% end %>

            <%= link_to "", articles_path, class: "glyphicon glyphicon-home icon" %>
          </ol>

          <h1><%= @article.title %></h1>
          <div class="post_commentbox"><i class="fa fa-user"><%= link_to @article.user.username, user_path(@article.user) %></i><span><i class="fa fa-calendar"></i><%= time_ago_in_words(@article.created_at) %> ago</span><i class="fa fa-tags"></i><%= render @article.categories %></a> </div>
          <div class="single_page_content">
            <%= (image_tag @article.picture.url, size: "275x200", class: "img-center") if @article.picture? %>
            <blockquote><%= @article.description %></blockquote>
          </div>

          <div class="single_page_content">
            <%= (video_tag @article.video.url, controls: true, type: ["video/mp4", "video/mp3", "video/mkv", "video/3gp"]) if @article.video? %>
          </div>

          <div class="single_page_content">
            <% if logged_in? %>
                <h3 style="color: black"><b>Comments:</b></h3>
                <hr />
                  <%= form_for([@article,@comment], remote: true, :html => {class: "form-horizontal", role: "form"}) do |f| %>
                    <div class="form-group">
                      <div class="control-label col-sm-2">
                        <%= f.label :Comment %><br/>
                      </div>

                      <div class="col-sm-8">
                        <p class="emoji-picker-container">
                          <%= f.text_area :description, class: 'form-control', data: { emojiable: true }, placeholder: "Enter Comment Here", rows:8 %>
                        </p>
                      </div>
                    </div>

                    <div class="form-group">
                      <div class="col-sm-offset-2 col-sm-10">
                        <%= f.submit "Submit Comment", class: "btn btn-primary btn-lg"%>
                      </div>
                    </div>
                  <% end %>
                  <hr />
            <% end %>

            <% if @article.comments != 0 %>
                <h3 style="color: black"><b>Prior Comments:</b></h3>
                <hr />
                  <div id="messages">
                    <%= render partial: 'comments/comments', object: @comments %>
                  </div>
            <% else %>
                <div class="row">
                  <div class="col-md-8 col-md-offset-2">
                    <h3>No Comments yet!</h3>
                  </div>
                </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="col-lg-4 col-md-4 col-sm-4">
      <aside class="right_content">
        <div class="single_sidebar">
          <h2><span>Latest News</span></h2>
          <marquee scrolldelay="" scrollamount="4" direction="up" onmouseover="this.setAttribute('scrollamount', 4, 0);" onmouseout="this.setAttribute('scrollamount', 4, 0);" behavior="scroll" height="600">
              <% @articles.each.with_index do |art, index| %>
                  <% if index != 0 %>
                      <div class="row" style="margin-bottom: 10px">
                        <div class="media col-md-4">
                          <%= link_to article_path(art) do %>
                              <%= image_tag(art.picture.url, height: '85', width: '100') if art.picture?%>
                          <% end %>
                        </div>
                        <div class="col-md-8" style="padding: 0;"><h4><%= link_to art.title, article_path(art) %></h4></div>
                      </div>
                <% end %>
            <% end %>
          </marquee>
        </div>
      </aside>
    </div>
  </div>
</section>