config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  get 'about', to: 'pages#about'

  resources :articles do
    member do
      put "like", to: "articles#upvote"
      put "dislike", to: "articles#downvote"
    end
    resources :comments, only: [:create, :destroy]
  end

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]

  mount ActionCable.server => '/cable'

  get '/chat', to: 'chatrooms#show'
  resources :messages, only: [:create]
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :article, through: :article_categories
  validates :name, presence: true, length: {minimum: 3, maximum: 25}
  validates_uniqueness_of :name


  def self.search(search)
    where("name LIKE ?", "%#{search}%")
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :require_admin, except: [:index, :show]

  def index
    #@categories = Category.paginate(page: params[:page], per_page: 6)
    @categories = Category.search(params[:search]).paginate(page: params[:page], per_page: 6).order("created_at DESC")
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was created successfully"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category name was successfully updated"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  def show
    @category = Category.find(params[:id])
    @category_articles = @category.article.paginate(page: params[:page], per_page: 4)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !logged_in? || (logged_in? and !current_user.admin?)
      flash[:danger] = "Only admin can perform that action"
      redirect_to categories_path
    end
  end
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %>  </span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>

    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :name %>
      </div>

      <div class="col-sm-8">
        <%= f.text_field :name, class: "form-control", placeholder: "Category name", autofocus: true %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: 'btn btn-primary btn-lg' %>
      </div>
    </div>

<% end %>

<div class="col-xs-4 col-xs-offset-4">
  [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
</div>

app/views/categories/edit.html.erb
<h1 align="center">Edit category Name</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<section id="sliderSection">

  <h1 align="center">Categories</h1>

  <% @categories.in_groups_of(3, false).each do |obj|%>
    <ul class="listing">
      <div class="row">
        <div class="cat_team">
          <% obj.each do |category| %>
            <div class="well col-md-3" style="margin-top: 50px; margin-right: 75px" align="center">
              <li class="article-title">

                <%= link_to category_path(category) do %>

                  <% if category.name == 'Social' %>
                    <%= image_tag("socialnews.png", :alt => "social.png") %>

                  <% elsif category.name == 'Business' %>
                     <%= image_tag("businessnews.jpg", :alt => "businessnews.jpg") %>

                  <% elsif category.name == 'Sports' %>
                    <%= image_tag("sportsnews.jpg", :alt => "sportsnews.jpg", height: "85px") %>

                  <% elsif category.name == 'Technology' %>
                    <%= image_tag("techno.jpg", :alt => "teco.jpg") %>

                  <% elsif category.name == 'Fashion' %>
                    <%= image_tag("fashion.jpg", :alt => "fashionnews.jpg") %>

                  <% else %>
                    <%= image_tag("lifestyle.jpg", size: '50x50') %>

                  <% end %>
                <% end %>
                <%= link_to "#{category.name}", category_path(category) %>
              </li>
              <li><small><%= pluralize(category.article.count, "article") %></small></li>
            </div>
          <% end %>
        </div>
      </div>
    </ul>
  <% end %>

  <div align="center">
    <%= will_paginate %>
  </div>


  <% if @categories.blank? %>
      <h4>There are no category containing the term <%= params[:search] %>.</h4>
  <% end %>

</section>

app/views/categories/new.html.erb
<h1 align="center">Create new category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 align="center"><%= "Category: " + @category.name %></h1>
<div align="center">
  <% if logged_in? and current_user.admin? %>
    <div class="row">
      <span class="badge"><%= link_to "Edit Category Name", edit_category_path(@category) %></span>
    </div>
  <% end %>

</div>

<%= render 'articles/cat', obj: @category_articles %>

<div align="center">
  <%= will_paginate @category_articles %>
</div>