config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  get 'about', to: 'pages#about'

  resources :articles do
    member do
      put "like", to: "articles#upvote"
      put "dislike", to: "articles#downvote"
    end
    resources :comments, only: [:create, :destroy]
  end

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]

  mount ActionCable.server => '/cable'

  get '/chat', to: 'chatrooms#show'
  resources :messages, only: [:create]
end

app/views/layouts/_footer.html.erb
<footer id="footer">
  <div class="footer_top">
    <div class="row">
      <div class="col-lg-4 col-md-4 col-sm-4">
        <div class="footer_widget wow fadeInLeftBig">
          <h2>Flickr Images</h2>
        </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-4">
        <div class="footer_widget wow fadeInDown">
          <h2>Tag</h2>
          <ul class="tag_nav">
            <li><%= link_to "News", articles_path %></li>
            <% if logged_in? %>
                <li><%= link_to "New News", new_article_path %></li>
            <% else %>
                <li><%= link_to "New News", login_path %></li>
            <% end %>


            <li><%= link_to "Agencies", users_path %></li>
            <li><%= link_to "UserChat", chat_path %></li>
            <% if logged_in? %>
              <li><%= link_to 'Log out', logout_path, method: :delete %></li>
            <% else %>
                <li><%= link_to 'Log in', login_path %></li>
                <li><%= link_to 'Sign up', signup_path %></li>
            <% end %>
          </ul>
        </div>
      </div>

      <div class="col-lg-4 col-md-4 col-sm-4">
        <div class="footer_widget wow fadeInRightBig">
          <h2>Contact</h2>
          <p>News Website for all.</p>
          <address>
            Perfect News, Town City 3333,Surat Phone: 123-326-789 Fax: 123-546-567
          </address>
        </div>
      </div>
    </div>
  </div>
  <div class="footer_bottom">
    <p class="copyright">News &copy; 2017 </p>
    <p class="developer" style="color: white">Developed By Lanetteam</p>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
        <div class='alert alert-<%="#{name}" %>'>
          <a href="#" class="close" data-dismiss="alert">×</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "News", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if logged_in? %>
          <li><%= link_to "New News", new_article_path %></li>
        <% else %>
          <li><%= link_to "New News", login_path %></li>
        <% end %>

        <% if logged_in? %>
          <li><%= link_to "Agencies", users_path %></li>
            <li><%= link_to "UserChat", chat_path %></li>
        <% end %>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All Categories", categories_path %></li>
            <% Category.all.each do |category| %>
                <li><%= link_to "#{category.name}", category_path(category) %></li>
            <% end %>

            <% if logged_in? and current_user.admin? %>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Create New Category", new_category_path %></li>
            <% end %>
          </ul>
        </li>

        <li style="margin-top: 12px">
          <%#= form_tag(categories_path, :method => "get", id: "search-form") do %>
            <%#= text_field_tag :search, params[:search], placeholder: "Search" %>
            <%#= submit_tag "Search", :name => nil %>


          <%= form_tag(articles_path, :method => "get", id: "search-form") do %>
              <%= text_field_tag :search, params[:search], placeholder: "Search" %>
              <%= submit_tag "Search", :name => nil %>
          <% end %>
        </li>
      </ul>


      <!--<form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>-->

      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to 'Log out', logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile <%= "Admin" if current_user.admin? %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit your profile", edit_user_path(current_user) %></li>
              <li><%= link_to "View profile", user_path(current_user) %></li>
              <!--<li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>-->
            </ul>
          </li>
        <% else %>
            <li><%= link_to 'Log in', login_path %></li>
            <li><%= link_to 'Sign up', signup_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewsApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>